### ISSUE TITLE
有意义

### ISSUE THREAD

**Issue by jdjshhc** [0011000000110010/obsidian-i18n#1]
1. 我觉得很有意义，特别是对于我这种看见英语就难受的人来说
2. 可以尝试联系官方，从插件设计开始就遵循i18n
3. 我测试了两个插件，calendar，mysnippets，翻译过后都变成空白

**Comment by 0011000000110010** [comment]
我在obsidian中文论坛更新了使用教程 里面有讲这种情况
[链接](https://forum-zh.obsidian.md/t/topic/30190)
