### ISSUE TITLE
无法正常启用i18n

### ISSUE THREAD

**Issue by atlantis414** [0011000000110010/obsidian-i18n#11]
![捕获](https://github.com/user-attachments/assets/54c2f5cf-d794-4f1a-b761-acaf0dd838ec)

第一次使用obsidian,不知是否有未设置的地方.
按照教程

> 输入 https://github.com/0011000000110010/obsidian-i18n

后, 就出现方块字界面, 没有如B站视频中的效果

**Comment by dangehub** [comment]
中文没有正常显示，感觉是你系统的问题。这是用的linux？

**Comment by atlantis414** [comment]
群晖6.2.3中docker运行的obsidian

**Comment by dangehub** [comment]
> 群晖6.2.3中docker运行的obsidian obsidian 1.6.7

那你可以去测试其他中文界面有没有同样的问题，如果确定是系统的问题，就去解决系统的问题

**Comment by atlantis414** [comment]
> > 群晖6.2.3中docker运行的obsidian obsidian 1.6.7
> 
> 那你可以去测试其他中文界面有没有同样的问题，如果确定是系统的问题，就去解决系统的问题

....那肯定是其他docker有中文的都妥妥没问题, 如果有的话我肯定先解决.

**Comment by atlantis414** [comment]
> To install cjk fonts on startup as an example pass the environment variables:
> 
> -e DOCKER_MODS=linuxserver/mods:universal-package-install
> -e INSTALL_PACKAGES=fonts-noto-cjk
> -e LC_ALL=zh_CN.UTF-8
