### ISSUE TITLE
希望增加对于主题设置的汉化功能

### ISSUE THREAD

**Issue by adiyaojz** [0011000000110010/obsidian-i18n#14]
需要修改title与description参数即可
![Clip_2024-11-12_10-45-22](https://github.com/user-attachments/assets/2127380d-d691-4646-a706-c3c764110e84)
就会有如下效果
![Clip_2024-11-12_10-45-42](https://github.com/user-attachments/assets/49965b3d-b8b3-424b-80d7-ec274cb18699)
具体文件路径为
.obsidian/themes路径下的子文件中的theme.css中

**Comment by adiyaojz** [comment]
[description.txt](https://github.com/user-attachments/files/17711123/description.txt)
[theme - 副本.txt](https://github.com/user-attachments/files/17711124/theme.-.txt)
[title.txt](https://github.com/user-attachments/files/17711126/title.txt)

**Comment by 0011000000110010** [comment]
群里已经有测试版了，可以加群测试一下，如果新版本功能没问题可能今晚会上
