### ISSUE TITLE
希望开启库的时候i18n不要跳那么多的提示

### ISSUE THREAD

**Issue by jiajiala** [0011000000110010/obsidian-i18n#16]
每次开启库，18n都要跳很多提示，让人烦躁
而且都是没必要跳的提示……
每次都让我想关掉它……

不过还是谢谢大佬的插件！！

**Comment by 0011000000110010** [comment]
不想让他眺提示，那么你把对应的功能关了就好了，更新那有开关，云端那也有开关，启动显示秒数同样有开关，除了这几个似乎就没跳提示的了吧(暂时只能想到这几个)

**Comment by jiajiala** [comment]
原来都可以关，跳的很多，完全看不清跳的内容就闪过去了，谢谢大佬

**Comment by jiajiala** [comment]
![image](https://github.com/user-attachments/assets/16894018-c6cd-4f6d-baa0-1309a3984bb4)
像这些功能我是需要的，但是不希望它每次都跳出来，对我来说并没有什么用，成功是一个正常运行的状态，不需要提醒我，如果有错误，或者有新版本再提醒我，每次开都跳一堆的提醒，反而让真正有用的提醒不容易被看到了
希望大佬能够支持关闭这些提醒，其他插件基本都是错误的时候才有提醒
谢谢了

**Comment by 0011000000110010** [comment]
智能更新去掉问题不大，但是这个云端不太好弄，因为请求api有延迟存在，直接关了也不太好，后续有时间或许可以加个可开关的通知吧，但是优先级不高，前面还有不少功能没实现，加上我最近也没什么时间。(这个智能更新，其实用到的时候不多，如果觉得烦，可以关下，标记汉化其实也可以关了，那个提交标记之前被删了，所以能标记数量有限。)

**Comment by 0011000000110010** [comment]
功能已添加。

**Comment by dangehub** [comment]
其实这个插件最好的使用办法是，你把你需要翻译的插件全部翻译完之后，就把i18n关掉。因为i18n的工作原理不需要持续开启。

**Comment by jiajiala** [comment]
> 其实这个插件最好的使用办法是，你把你需要翻译的插件全部翻译完之后，就把i18n关掉。因为i18n的工作原理不需要持续开启。

我以为开着会跟着插件的更新实时更新呢…不是么？

**Comment by dangehub** [comment]
> > 其实这个插件最好的使用办法是，你把你需要翻译的插件全部翻译完之后，就把i18n关掉。因为i18n的工作原理不需要持续开启。
> 
> 我以为开着会跟着插件的更新实时更新呢…不是么？

只会帮你标注更新后的插件有没有更新的译文，需要你手动点更新的。因为涉及到修改插件源码，最终的决定权还是要在用户手上的。

**Comment by 0011000000110010** [comment]
> > > 其实这个插件最好的使用办法是，你把你需要翻译的插件全部翻译完之后，就把i18n关掉。因为i18n的工作原理不需要持续开启。
> > 
> > 
> > 我以为开着会跟着插件的更新实时更新呢…不是么？
> 
> 只会帮你标注更新后的插件有没有更新的译文，需要你手动点更新的。因为涉及到修改插件源码，最终的决定权还是要在用户手上的。

其实现在不少功能都需要依赖插件，检查更新、名称翻译、云端译文更新、标记汉化、智能更新、还有审核之类的，需要用到这些功能一直开着也没问题，我还加了个启动耗时可以看到插件启动需要多久，大概0.003s，也不会占用太多性能，不是以前那样启动后需要等待请求了
