### ISSUE TITLE
无法通过 BRAT 插件安装此插件

### ISSUE THREAD

**Issue by Benature** [0011000000110010/obsidian-i18n#2]
> [BRAT](https://github.com/TfTHacker/obsidian42-brat) 是测试 beta 插件的一个插件
<img width="309" alt="image" src="https://github.com/0011000000110010/obsidian-i18n/assets/35028647/26d42750-8e2d-40b1-8c74-a6d01ea36d1a">

---

- 另外我看到 release 中的 tag 是 `v` 开头的，这在 Obsidian 官方文档中并不允许。
- 发布 release 建议可以用 Github Action 来自动化，比如可以参考 https://github.com/Benature/obsidian-share-my-plugin-list/blob/master/.github/workflows/release.yml

**Comment by 0011000000110010** [comment]
1. 因为我没有事先查阅Obsidian插件的发布流程，所以在上传时未能按照Obsidian的官方文档进行操作。
2. 关于BRAT插件的提示问题，我怀疑可能也是由于我在打包发布文件时，未能按照Obsidian的官方文档进行操作所造成的。
3. 由于我是第一次使用Github，对其中的Github Actions等功能也不是很了解。

为了确保问题得到妥善解决，我会尽快查阅相关文档，并严格按照Obsidian插件的发布流程进行重新发布。

**Comment by cuberwu** [comment]
似乎需要修改根目录下manifest.json的版本号使BRAT安装时指向最新版本，现在自动下的是旧版本的
