### ISSUE TITLE
修改提取方式

### ISSUE THREAD

**Issue by samiytaa** [0011000000110010/obsidian-i18n#20]

**Comment by samiytaa** [comment]
![image](https://github.com/user-attachments/assets/615dbefc-a59e-4c49-83f1-3272234f7ab5)
在一个插件之中，只有description被插件提取了，其他的地方没有提取，要回到主文件中才能修改

**Comment by 0011000000110010** [comment]
主题我记得只会提取两个字段 一个description 还有一个什么忘了

**Comment by 0011000000110010** [comment]
这个插件应该是没有后续了，修改源代码的操作就是不允许，解决办法他们也不想，就是只是加个建议,加不加i18n全抛给开发者，开发者呢就死等PR,那边和他们一讨论，甚至还有什么给插件加验证的想法，我也不想管他们这些事了，完全是给自己添堵。如果有能力的话可以看下源码自己改改。

**Comment by samiytaa** [comment]
> 这个插件应该是没有后续了，修改源代码的操作就是不允许，解决办法他们也不想，就是只是加个建议,加不加i18n全抛给开发者，开发者呢就死等PR,那边和他们一讨论，甚至还有什么给插件加验证的想法，我也不想管他们这些事了，完全是给自己添堵。如果有能力的话可以看下源码自己改改。

好的，多谢
