### ISSUE TITLE
能否出个教程呢

### ISSUE THREAD

**Issue by gitby2018** [0011000000110010/obsidian-i18n#3]
很不好意思的，我用你的插件尝试了好几次，也去申请了百度翻译api，可是无论怎么弄，根本都没有翻译成功，文字依旧是英文，要不就是重启后提示插件无法启动。我不知道是我对你的文字教程理解有误，还是我什么地方操作有问题。请求能否出个视频操作教程？或者图文版的流程？辛苦你了

**Comment by 0011000000110010** [comment]
中文论坛中已更新视频演示教程 https://forum-zh.obsidian.md/t/topic/30190 百度API翻译后无法使用 可能是因为当时我写代码的时候没有给无法翻译的字段一个内容 导致代码被替换为空 所以会导致插件失效的问题 需要自行去翻译文件中删除或者将代码翻译一下 因为这段时间比较忙 我可能暂时无法更新插件
