### ISSUE TITLE
建议：增加关于插件描述的翻译

### ISSUE THREAD

**Issue by denastria** [0011000000110010/obsidian-i18n#5]
非常好用，感谢开发者大大🙏。
提个建议，希望支持汉化插件的描述字段。
![Snipaste_2024-09-01_07-25-01](https://github.com/user-attachments/assets/f7788355-993c-43bf-8645-40a0debf0801)
![Snipaste_2024-09-01_07-26-00](https://github.com/user-attachments/assets/6c9d1d05-fd7a-4b02-a938-5c1040100e0f)
![Snipaste_2024-09-01_07-23-57](https://github.com/user-attachments/assets/0ed20b47-25fe-413f-9bbf-9f5316680244)
![Snipaste_2024-09-01_07-26-46](https://github.com/user-attachments/assets/80d36bf8-20c5-483d-8b64-ba972bf211ba)

**Comment by 0011000000110010** [comment]
建议已收到 如果要加入汉化描述字段的话需要改的地方比较多 这几天我可能暂时没有时间 有时间的话会加入此功能

**Comment by denastria** [comment]
> 建议已收到 如果要加入汉化描述字段的话需要改的地方比较多 这几天我可能暂时没有时间 有时间的话会加入此功能

也不是很紧急的需求 能考虑添加太好啦 很期待
