### ISSUE TITLE
现在glm-4-flash 免费API了，可否支持一下，另外，我用网络接口模式，为什么翻译不了

### ISSUE THREAD

**Issue by plhys** [0011000000110010/obsidian-i18n#6]
我填入了百度翻译的id和key，点击翻译，但是并没有翻译过程，只是让我重启，重启后还是没有翻译

**Comment by plhys** [comment]
折腾了一晚上，还是不能自动翻译

**Comment by 0011000000110010** [comment]
能说下具体哪里有问题吗，我这里测试了下 是正常的

**Comment by 0011000000110010** [comment]
填入百度的api 
点击蓝色的生成 
生成后会有一个翻译的按钮 
点击翻译 
然后重启Obsidian
您看下您是这个流程吗

**Comment by 0011000000110010** [comment]
至于接入ai的话是可以接入 只是我无法判断ai生成的准确性 可能会导致整个译文json格式的失效 如果你有什么比较好的建议可以提下
