### ISSUE TITLE
bug | 部分未知的情况下编辑翻译内容后保存会失效，但会在尾部追加新翻译的内容

### ISSUE THREAD

**Issue by nathandingx** [0011000000110010/obsidian-i18n#8]
部分未知的情况下编辑翻译内容后保存会失效，但会在尾部追加新翻译的内容

现在情况是，我把不能修改的内容、自动追加的内容都删除了，我没办法恢复原来我希望修改的内容，我想重新翻译但不知道原文是什么

希望能有个不破坏已翻译的内容，重新拉取所有可翻译内容的按钮

**Comment by 0011000000110010** [comment]
1. 不能保存的问题，建议附带截图或者视频，这样我方便定位问题所在位置
2. 第二个问题 可以直接打开译文文件进行编辑 去main.js中查找对应的字段
3. 如果可以的话 我会添加此功能

**Comment by nathandingx** [comment]
我编辑的是插件【Omnisearch】中【.setDesc("Navigate down the results with Ctrl/Au2318 + J/N, or navigate up with Ctrl/\u2318 + K/P ")】这段文本的翻译，原始的那一条因为bug被我删除找不到了，只截了一张最后自动追加的文本图片

![Snipaste_2024-09-30_14-24-23](https://github.com/user-attachments/assets/8d192470-7428-4914-93bb-4c7ad838e865)

**Comment by 0011000000110010** [comment]
看你翻译的这个 你用的是macOS吗

**Comment by nathandingx** [comment]
windows，它这个应该是转义字符



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月30日(周一) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [0011000000110010/obsidian-i18n] bug | 部分未知的情况下编辑翻译内容后保存会失效，但会在尾部追加新翻译的内容 (Issue #8)




 
看你翻译的这个 你用的是macOS吗

**Comment by nathandingx** [comment]
我翻译的时候输入的是原文ASCII码，保存后自动变图标了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月30日(周一) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [0011000000110010/obsidian-i18n] bug | 部分未知的情况下编辑翻译内容后保存会失效，但会在尾部追加新翻译的内容 (Issue #8)




 
看你翻译的这个 你用的是macOS吗

**Comment by 0011000000110010** [comment]
等下我上传个新版本 如果还会出现这种问题 建议录个视频，自动添加字段这个问题，我有些懵，按理来说是不应该出现的
